"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Sidebar from "../components/sidebar";
import { deleteRemote, loadRemote, saveRemote } from "../lib/remote-records";

type ClientForm = {
  clientId: string; serviceDate: string; fullName: string; dateOfBirth: string; last4Ssn: string; ethnicity: string; gender: string;
  address: string; city: string; state: string; zip: string; phone: string; email: string; nationality: string;
  householdSize: string; children: string; adults: string; seniors: string; spouseName: string; maritalStatus: string;
  immigrationStatus: string; income: string; socialServices: boolean; otherServices: boolean; immigration: boolean;
  healthAndWellness: boolean; workersResourceCenter: boolean; educationalEmpowerment: boolean; photo: string; files: string[]; caseNotes: string;
};
type Client = ClientForm & { id: string; createdAt: string };
type LegacyRow = Record<string, string>;
const storageKey = "uccw_clients";
const initialForm: ClientForm = { clientId: "", serviceDate: "", fullName: "", dateOfBirth: "", last4Ssn: "", ethnicity: "", gender: "", address: "", city: "", state: "", zip: "", phone: "", email: "", nationality: "", householdSize: "", children: "", adults: "", seniors: "", spouseName: "", maritalStatus: "", immigrationStatus: "", income: "", socialServices: false, otherServices: false, immigration: false, healthAndWellness: false, workersResourceCenter: false, educationalEmpowerment: false, photo: "", files: ["", "", "", "", ""], caseNotes: "" };

function normalize(item: Partial<Client> & { name?: string }): Client { const id = item.id || crypto.randomUUID(); return { ...initialForm, ...item, clientId: item.clientId || `C-${id.slice(0, 8).toUpperCase()}`, fullName: item.fullName || item.name || "", files: item.files?.length ? item.files : ["", "", "", "", ""], id, createdAt: item.createdAt || new Date().toISOString() }; }
function nextId(clients: Client[]) { const highest = clients.reduce((max, client) => Math.max(max, Number(client.clientId.match(/\d+$/)?.[0]) || 0), 0); return `C-${String(highest + 1).padStart(5, "0")}`; }

export default function ClientManager() {
  const [clients, setClients] = useState<Client[]>([]); const [search, setSearch] = useState(""); const [isFormOpen, setIsFormOpen] = useState(false); const [editingClient, setEditingClient] = useState<Client | null>(null); const [form, setForm] = useState<ClientForm>(initialForm); const [importStatus, setImportStatus] = useState(""); const importRef = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; try { const local = JSON.parse(window.localStorage.getItem(storageKey) || "[]").map(normalize); loadRemote<Client>("clients", local).then((records) => { if (active) { setClients(records.map(normalize)); try { window.localStorage.setItem(storageKey, JSON.stringify(records)); } catch { /* Supabase remains the source of truth for large imports. */ } } }); } catch { setClients([]); } return () => { active = false; }; }, []);
  function persist(next: Client[]) { setClients(next); try { window.localStorage.setItem(storageKey, JSON.stringify(next)); } catch { /* Supabase remains the source of truth for large imports. */ } }
  function update<K extends keyof ClientForm>(key: K, value: ClientForm[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function openNew() { setEditingClient(null); setForm({ ...initialForm, files: ["", "", "", "", ""] }); setIsFormOpen(true); }
  function openEdit(client: Client) { setEditingClient(client); setForm({ ...client, files: [...client.files] }); setIsFormOpen(true); }
  function updateFile(index: number, name: string) { const files = [...form.files]; files[index] = name; update("files", files); }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const record = editingClient ? { ...editingClient, ...form } : { id: crypto.randomUUID(), createdAt: new Date().toISOString(), ...form, clientId: nextId(clients) }; persist(editingClient ? clients.map((client) => client.id === editingClient.id ? record : client) : [record, ...clients]); saveRemote("clients", record); setIsFormOpen(false); }
  function remove(client: Client) { if (window.confirm(`¿Eliminar el cliente ${client.fullName}?`)) { persist(clients.filter((item) => item.id !== client.id)); deleteRemote("clients", client.id); } }
  async function importClients(file: File) {
    const rows = parseCsv(await file.text()); const imported = rows.map(importRow).filter((item): item is Client => Boolean(item));
    if (!imported.length) { setImportStatus("No se encontraron clientes válidos en el archivo."); return; }
    if (!window.confirm(`Se importarán ${imported.length} clientes válidos. Las filas sin nombre se omitirán. ¿Desea continuar?`)) return;
    setImportStatus(`Importando 0 de ${imported.length} clientes…`);
    try {
      for (let index = 0; index < imported.length; index += 200) {
        const response = await fetch("/api/records/clients", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ records: imported.slice(index, index + 200) }) });
        if (!response.ok) throw new Error(); setImportStatus(`Importando ${Math.min(index + 200, imported.length)} de ${imported.length} clientes…`);
      }
      const byClientId = new Map(clients.map((item) => [item.clientId, item])); imported.forEach((item) => byClientId.set(item.clientId, item)); persist([...byClientId.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt))); setImportStatus(`${imported.length} clientes importados correctamente.`);
    } catch { setImportStatus("No fue posible completar la importación. No se eliminaron los registros ya guardados; vuelva a intentar el archivo."); }
  }
  const visible = useMemo(() => { const text = search.trim().toLowerCase(); return text ? clients.filter((client) => [client.fullName, client.last4Ssn, client.phone, client.email, client.city].some((value) => value.toLowerCase().includes(text))) : clients; }, [clients, search]);
  return <main className="app-shell clients-page"><Sidebar active="clientes" /><section className="clients-content">
    <div className="page-heading"><div><p className="eyebrow">Administración</p><h1>Clientes</h1><p>Registra y consulta la información de cada cliente.</p></div><div className="heading-actions"><input ref={importRef} type="file" accept=".csv,text/csv" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void importClients(file); event.currentTarget.value = ""; }} /><button type="button" className="secondary-button" onClick={() => importRef.current?.click()}>Importar CSV</button><button onClick={openNew}>+ Nuevo cliente</button></div></div>
    <div className="clients-toolbar"><input aria-label="Buscar clientes" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre, últimos 4 SSN, ciudad, correo o teléfono" /><span>{visible.length} cliente{visible.length === 1 ? "" : "s"}</span></div>
    {importStatus && <p className="storage-note">{importStatus}</p>}
    <div className="table-card">{visible.length === 0 ? <div className="empty-state"><h2>No hay clientes registrados</h2><p>Agrega el primer cliente para comenzar.</p></div> : <table><thead><tr><th>Client ID</th><th>Cliente</th><th>Fecha de servicio</th><th>Ubicación</th><th>Contacto</th><th>Servicios</th><th aria-label="Acciones"></th></tr></thead><tbody>{visible.map((client) => <tr key={client.id}><td>{client.clientId}</td><td><strong>{client.fullName}</strong><small>SSN: {client.last4Ssn || "No indicado"}</small></td><td>{client.serviceDate || "No indicada"}</td><td><span>{client.city || "Sin ciudad"}</span><small>{client.state} {client.zip}</small></td><td><span>{client.email || "Sin correo"}</span><small>{client.phone || "Sin teléfono"}</small></td><td>{[client.socialServices && "Social", client.immigration && "Immigration", client.healthAndWellness && "Health"].filter(Boolean).join(", ") || "No asignados"}</td><td className="actions"><button className="text-button" onClick={() => openEdit(client)}>Editar</button><button className="text-button danger" onClick={() => remove(client)}>Eliminar</button></td></tr>)}</tbody></table>}</div>
    <p className="storage-note">Los expedientes se sincronizan con la base de datos central. Por seguridad, el sistema solo conserva los últimos cuatro dígitos del SSN.</p>
  </section>{isFormOpen && <ClientFormModal form={form} editing={Boolean(editingClient)} update={update} updateFile={updateFile} close={() => setIsFormOpen(false)} save={save} />}</main>;
}

function parseCsv(text: string): LegacyRow[] { const lines: string[][] = [[]]; let value = ""; let quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { lines.at(-1)?.push(value); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index += 1; lines.at(-1)?.push(value); value = ""; lines.push([]); } else value += char; } lines.at(-1)?.push(value); const [headers = [], ...data] = lines; return data.filter((row) => row.some((cell) => cell.trim())).map((row) => Object.fromEntries(headers.map((header, index) => [header.trim(), (row[index] || "").trim()]))); }
function value(row: LegacyRow, key: string) { const item = row[key]?.trim() || ""; return item === "-" ? "" : item; }
function hasValue(row: LegacyRow, key: string) { return Boolean(value(row, key)); }
function dateValue(row: LegacyRow, key: string) { const item = value(row, key); return /^\d{4}-\d{2}-\d{2}$/.test(item) ? item : ""; }
function numberValue(row: LegacyRow, key: string) { return value(row, key).replace(/[^\d.]/g, ""); }
function importRow(row: LegacyRow): Client | null { const sourceId = value(row, "ClientID"); const fullName = value(row, "Full_Name"); if (!sourceId || !fullName) return null; const digits = value(row, "SSN").replace(/\D/g, ""); const notes = [value(row, "Notes"), value(row, "Service_Notes"), value(row, "Comments"), value(row, "Comment")].filter(Boolean).join("\n\n"); const legacyData = Object.fromEntries(Object.entries(row).filter(([key]) => key !== "SSN")); return { ...initialForm, id: crypto.randomUUID(), createdAt: new Date().toISOString(), clientId: `C-${sourceId}`, serviceDate: dateValue(row, "Service_Date"), fullName, dateOfBirth: dateValue(row, "DOB"), last4Ssn: digits.slice(-4), ethnicity: value(row, "Ethinicity"), gender: value(row, "Gender"), address: value(row, "Address"), city: value(row, "City"), state: value(row, "State"), zip: value(row, "Zip"), phone: value(row, "Phone"), email: value(row, "Email"), nationality: value(row, "Nationality"), householdSize: numberValue(row, "Household_Size"), children: numberValue(row, "Children"), adults: numberValue(row, "Adults"), seniors: numberValue(row, "Seniors"), spouseName: value(row, "Spouse_Name"), maritalStatus: value(row, "Marital_Status"), immigrationStatus: value(row, "Immigration_Status"), income: numberValue(row, "Income"), socialServices: hasValue(row, "Social_Services"), otherServices: hasValue(row, "Other_Svcs"), immigration: hasValue(row, "Immigration"), healthAndWellness: hasValue(row, "Health"), workersResourceCenter: hasValue(row, "Workers_Resource"), educationalEmpowerment: hasValue(row, "Education"), caseNotes: notes, legacyData } as Client; }

function ClientFormModal({ form, editing, update, updateFile, close, save }: { form: ClientForm; editing: boolean; update: <K extends keyof ClientForm>(key: K, value: ClientForm[K]) => void; updateFile: (index: number, name: string) => void; close: () => void; save: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-backdrop" role="presentation"><section className="modal client-modal" role="dialog" aria-modal="true" aria-labelledby="client-form-title"><div className="modal-heading"><h2 id="client-form-title">{editing ? "Editar cliente" : "Nuevo cliente"}</h2><button className="close-button" aria-label="Cerrar" onClick={close}>×</button></div><form onSubmit={save}>
    <h3>Información de servicio</h3><div className="form-grid"><Field label="Client ID"><input value={form.clientId || "Se genera al guardar"} readOnly /></Field><Field label="Service Date"><input type="date" value={form.serviceDate} onChange={(e) => update("serviceDate", e.target.value)} required /></Field><Field label="Full Name"><input value={form.fullName} onChange={(e) => update("fullName", e.target.value)} required /></Field><Field label="Date Of Birth"><input type="date" value={form.dateOfBirth} onChange={(e) => update("dateOfBirth", e.target.value)} /></Field><Field label="Last 4 SSN"><input inputMode="numeric" maxLength={4} value={form.last4Ssn} onChange={(e) => update("last4Ssn", e.target.value.replace(/\D/g, "").slice(0, 4))} /></Field><Field label="Ethnicity"><input value={form.ethnicity} onChange={(e) => update("ethnicity", e.target.value)} /></Field><Field label="Gender"><select value={form.gender} onChange={(e) => update("gender", e.target.value)}><option value="">Seleccione</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></Field></div>
    <h3>Dirección y contacto</h3><div className="form-grid"><Field label="Address" full><input value={form.address} onChange={(e) => update("address", e.target.value)} /></Field><Field label="City"><input value={form.city} onChange={(e) => update("city", e.target.value)} /></Field><Field label="State"><input value={form.state} onChange={(e) => update("state", e.target.value)} /></Field><Field label="Zip"><input value={form.zip} onChange={(e) => update("zip", e.target.value)} /></Field><Field label="Phone"><input value={form.phone} onChange={(e) => update("phone", e.target.value)} /></Field><Field label="Email" full><input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></Field><Field label="Nationality"><input value={form.nationality} onChange={(e) => update("nationality", e.target.value)} /></Field></div>
    <h3>Hogar e información personal</h3><div className="form-grid"><Field label="Household Size"><input type="number" min="0" value={form.householdSize} onChange={(e) => update("householdSize", e.target.value)} /></Field><Field label="Children"><input type="number" min="0" value={form.children} onChange={(e) => update("children", e.target.value)} /></Field><Field label="Adults"><input type="number" min="0" value={form.adults} onChange={(e) => update("adults", e.target.value)} /></Field><Field label="Seniors"><input type="number" min="0" value={form.seniors} onChange={(e) => update("seniors", e.target.value)} /></Field><Field label="Spouse Name"><input value={form.spouseName} onChange={(e) => update("spouseName", e.target.value)} /></Field><Field label="Marital Status"><input value={form.maritalStatus} onChange={(e) => update("maritalStatus", e.target.value)} /></Field><Field label="Immigration Status"><input value={form.immigrationStatus} onChange={(e) => update("immigrationStatus", e.target.value)} /></Field><Field label="Income $"><input type="number" min="0" step="0.01" value={form.income} onChange={(e) => update("income", e.target.value)} /></Field></div>
    <h3>Servicios solicitados</h3><div className="service-grid"><Check label="Social Services" checked={form.socialServices} onChange={(v) => update("socialServices", v)} /><Check label="Other Services" checked={form.otherServices} onChange={(v) => update("otherServices", v)} /><Check label="Immigration" checked={form.immigration} onChange={(v) => update("immigration", v)} /><Check label="Health And Wellness" checked={form.healthAndWellness} onChange={(v) => update("healthAndWellness", v)} /><Check label="Workers Resource Center" checked={form.workersResourceCenter} onChange={(v) => update("workersResourceCenter", v)} /><Check label="Educational Empowerment" checked={form.educationalEmpowerment} onChange={(v) => update("educationalEmpowerment", v)} /></div>
    <h3>Foto, archivos y notas</h3><PhotoCapture photo={form.photo} updatePhoto={(photo) => update("photo", photo)} /><div className="file-grid">{form.files.map((file, index) => <label className="file-field" key={index}>File{index + 1}<span>{file || "Sin archivos seleccionados"}</span><input type="file" onChange={(e) => updateFile(index, e.target.files?.[0]?.name || "")} /><small>Choose file to upload</small></label>)}</div><Field label="Case Notes" full><textarea rows={4} value={form.caseNotes} onChange={(e) => update("caseNotes", e.target.value)} /></Field>
    <div className="form-actions"><button type="button" className="cancel-button" onClick={close}>Cancelar</button><button type="submit">{editing ? "Guardar cambios" : "Registrar cliente"}</button></div>
  </form></section></div>;
}
function Field({ label, children, full = false }: { label: string; children: React.ReactNode; full?: boolean }) { return <label className={full ? "full-width" : ""}>{label}{children}</label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="service-check"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />{label}</label>; }
function PhotoCapture({ photo, updatePhoto }: { photo: string; updatePhoto: (photo: string) => void }) {
  const videoRef = useRef<HTMLVideoElement>(null); const [stream, setStream] = useState<MediaStream | null>(null); const [cameraError, setCameraError] = useState("");
  function stopCamera() { stream?.getTracks().forEach((track) => track.stop()); setStream(null); }
  async function openCamera() { try { setCameraError(""); setStream(await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false })); } catch { setCameraError("No se pudo acceder a la cámara. Verifique los permisos del navegador."); } }
  function takePhoto() { const video = videoRef.current; if (!video) return; const canvas = document.createElement("canvas"); canvas.width = video.videoWidth || 640; canvas.height = video.videoHeight || 480; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); updatePhoto(canvas.toDataURL("image/jpeg", 0.8)); stopCamera(); }
  useEffect(() => { if (stream && videoRef.current) { videoRef.current.srcObject = stream; videoRef.current.play().catch(() => setCameraError("No se pudo iniciar la cámara.")); } return () => { stream?.getTracks().forEach((track) => track.stop()); }; }, [stream]);
  return <div className="photo-capture"><strong>Foto</strong>{photo && <img src={photo} alt="Foto del cliente" />} {stream && <video ref={videoRef} muted playsInline />}<div><button type="button" className="secondary-button" onClick={stream ? takePhoto : openCamera}>{stream ? "Tomar fotografía" : "Abrir cámara"}</button>{stream && <button type="button" className="text-button" onClick={stopCamera}>Cancelar cámara</button>}{photo && <button type="button" className="text-button danger" onClick={() => updatePhoto("")}>Eliminar foto</button>}</div>{cameraError && <small className="form-error">{cameraError}</small>}</div>;
}
