"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Sidebar from "../components/sidebar";
import { deleteRemote, loadRemote, saveRemote } from "../lib/remote-records";

type ClientForm = {
  clientId: string; serviceDate: string; fullName: string; dateOfBirth: string; last4Ssn: string; ethnicity: string; gender: string;
  address: string; city: string; state: string; zip: string; phone: string; email: string; nationality: string;
  householdSize: string; children: string; adults: string; seniors: string; spouseName: string; maritalStatus: string;
  immigrationStatus: string; income: string; socialServices: boolean; otherServices: boolean; immigration: boolean;
  healthAndWellness: boolean; workersResourceCenter: boolean; educationalEmpowerment: boolean; photo: string; files: string[]; caseNotes: string;
};
type LegacyData = Record<string, unknown>;
type Client = ClientForm & { id: string; createdAt: string; createdBy?: string; updatedAt?: string; updatedBy?: string; legacyData?: LegacyData; legacySources?: LegacyData[] };
type ServiceRecord = { id?: string; date?: string; fullName?: string; address?: string; children?: string; adults?: string; seniors?: string; totalHousehold?: string; createdAt?: string };
type LegacyRow = Record<string, string>;
const storageKey = "uccw_clients";
const initialForm: ClientForm = { clientId: "", serviceDate: "", fullName: "", dateOfBirth: "", last4Ssn: "", ethnicity: "", gender: "", address: "", city: "", state: "", zip: "", phone: "", email: "", nationality: "", householdSize: "", children: "", adults: "", seniors: "", spouseName: "", maritalStatus: "", immigrationStatus: "", income: "", socialServices: false, otherServices: false, immigration: false, healthAndWellness: false, workersResourceCenter: false, educationalEmpowerment: false, photo: "", files: ["", "", "", "", ""], caseNotes: "" };

function normalize(item: Partial<Client> & { name?: string }): Client { const id = item.id || crypto.randomUUID(); return { ...initialForm, ...item, clientId: item.clientId || `C-${id.slice(0, 8).toUpperCase()}`, fullName: item.fullName || item.name || "", files: item.files?.length ? item.files : ["", "", "", "", ""], id, createdAt: item.createdAt || new Date().toISOString() }; }
function nextId(clients: Client[]) { const highest = clients.reduce((max, client) => Math.max(max, Number(client.clientId.match(/\d+$/)?.[0]) || 0), 0); return `C-${String(highest + 1).padStart(5, "0")}`; }
function readLocal<T>(key: string): T[] { try { return JSON.parse(window.localStorage.getItem(key) || "[]") as T[]; } catch { return []; } }
function normalizedName(name: string) { return name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\p{L}\p{N}]+/gu, " ").trim().toLowerCase(); }
function documentNames(client: Client) { const legacy = [client.legacyData, ...(client.legacySources || [])].filter(Boolean).flatMap((record) => Object.entries(record || {}).filter(([key, item]) => /^file\s*\d+$/i.test(key) && typeof item === "string" && item.trim()).map(([, item]) => String(item).trim())); return [...new Set([...client.files.filter(Boolean), ...legacy])]; }
function storedUrl(path: string) { return path.includes("/") && !path.startsWith("data:") ? `/api/files?path=${encodeURIComponent(path)}` : path; }
function fileLabel(path: string) { return path.split("/").at(-1)?.replace(/^[a-f0-9-]+-/i, "") || path; }

export default function ClientManager() {
  const [clients, setClients] = useState<Client[]>([]); const [search, setSearch] = useState(""); const [isFormOpen, setIsFormOpen] = useState(false); const [editingClient, setEditingClient] = useState<Client | null>(null); const [historyClient, setHistoryClient] = useState<Client | null>(null); const [historyServices, setHistoryServices] = useState({ food: [] as ServiceRecord[], clothing: [] as ServiceRecord[] }); const [form, setForm] = useState<ClientForm>(initialForm); const [pendingFiles, setPendingFiles] = useState<(File | null)[]>([null, null, null, null, null]); const [importStatus, setImportStatus] = useState(""); const importRef = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; loadRemote<Client>("clients").then((records) => { if (active) setClients(records.map(normalize)); }); return () => { active = false; }; }, []);
  useEffect(() => { let active = true; Promise.all([loadRemote<ServiceRecord>("food"), loadRemote<ServiceRecord>("clothing")]).then(([food, clothing]) => { if (active) setHistoryServices({ food, clothing }); }); return () => { active = false; }; }, []);
  function persist(next: Client[]) { setClients(next); }
  function update<K extends keyof ClientForm>(key: K, value: ClientForm[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function openNew() { setEditingClient(null); setPendingFiles([null, null, null, null, null]); setForm({ ...initialForm, files: ["", "", "", "", ""] }); setIsFormOpen(true); }
  function openEdit(client: Client) { setEditingClient(client); setPendingFiles([null, null, null, null, null]); setForm({ ...client, files: [...client.files] }); setIsFormOpen(true); }
  function updateFile(index: number, file: File | null) { const files = [...form.files]; files[index] = file?.name || files[index] || ""; const next = [...pendingFiles]; next[index] = file; setPendingFiles(next); update("files", files); }
  async function uploadFile(file: File, recordId: string) { const data = new FormData(); data.set("file", file); data.set("module", "clients"); data.set("recordId", recordId); const response = await fetch("/api/files", { method: "POST", body: data }); if (!response.ok) throw new Error(); return (await response.json() as { path: string }).path; }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const id = editingClient?.id || crypto.randomUUID(); try { const photo = form.photo.startsWith("data:") ? await (async () => { const blob = await (await fetch(form.photo)).blob(); return uploadFile(new File([blob], "foto-cliente.jpg", { type: "image/jpeg" }), id); })() : form.photo; const files = await Promise.all(form.files.map((file, index) => pendingFiles[index] ? uploadFile(pendingFiles[index]!, id) : file)); const record = editingClient ? { ...editingClient, ...form, id, photo, files } : { id, createdAt: new Date().toISOString(), ...form, photo, files, clientId: nextId(clients) }; persist(editingClient ? clients.map((client) => client.id === editingClient.id ? record : client) : [record, ...clients]); saveRemote("clients", record); setIsFormOpen(false); } catch { window.alert("No fue posible guardar uno de los archivos. Verifique que el almacenamiento seguro de Supabase esté configurado."); } }
  function remove(client: Client) { if (window.confirm(`¿Eliminar el cliente ${client.fullName}?`)) { persist(clients.filter((item) => item.id !== client.id)); deleteRemote("clients", client.id); } }
  async function importClients(file: File) {
    const rows = parseCsv(await file.text()); const imported = rows.map(importRow).filter((item): item is Client => Boolean(item));
    if (!imported.length) { setImportStatus("No se encontraron clientes válidos en el archivo."); return; }
    if (!window.confirm(`Se importarán ${imported.length} clientes válidos. Las filas sin nombre se omitirán. ¿Desea continuar?`)) return;
    setImportStatus(`Importando 0 de ${imported.length} clientes…`);
    try {
      // Se conservan las variantes históricas por Client ID. Lotes pequeños evitan
      // exceder el límite de tamaño de las solicitudes cuando hay notas extensas.
      const batchSize = 25;
      for (let index = 0; index < imported.length; index += batchSize) {
        const response = await fetch("/api/records/clients", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ records: imported.slice(index, index + batchSize), mergeExisting: true }) });
        if (!response.ok) throw new Error(); setImportStatus(`Importando ${Math.min(index + batchSize, imported.length)} de ${imported.length} clientes…`);
      }
      const byClientId = new Map(clients.map((item) => [item.clientId, item])); imported.forEach((item) => byClientId.set(item.clientId, item)); persist([...byClientId.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt))); setImportStatus(`${imported.length} clientes importados correctamente.`);
    } catch { setImportStatus("No fue posible completar la importación. No se eliminaron los registros ya guardados; vuelva a intentar el archivo."); }
  }
  const visible = useMemo(() => { const text = search.trim().toLowerCase(); return text ? clients.filter((client) => [client.fullName, client.last4Ssn, client.phone, client.email, client.city].some((value) => value.toLowerCase().includes(text))) : clients; }, [clients, search]);
  return <main className="app-shell clients-page"><Sidebar active="clientes" /><section className="clients-content">
    <div className="page-heading"><div><p className="eyebrow">Administración</p><h1>Clientes</h1><p>Registra y consulta la información de cada cliente.</p></div><div className="heading-actions"><input ref={importRef} type="file" accept=".csv,text/csv" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void importClients(file); event.currentTarget.value = ""; }} /><button type="button" className="secondary-button" onClick={() => importRef.current?.click()}>Importar CSV</button><button onClick={openNew}>+ Nuevo cliente</button></div></div>
    <div className="clients-toolbar"><input aria-label="Buscar clientes" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre, últimos 4 SSN, ciudad, correo o teléfono" /><span>{visible.length} cliente{visible.length === 1 ? "" : "s"}</span></div>
    {importStatus && <p className="storage-note">{importStatus}</p>}
    <div className="table-card">{visible.length === 0 ? <div className="empty-state"><h2>No hay clientes registrados</h2><p>Agrega el primer cliente para comenzar.</p></div> : <table><thead><tr><th>Client ID</th><th>Cliente</th><th>Fecha de servicio</th><th>Ubicación</th><th>Contacto</th><th>Servicios</th><th aria-label="Acciones"></th></tr></thead><tbody>{visible.map((client) => <tr key={client.id}><td>{client.clientId}</td><td><strong>{client.fullName}</strong><small>SSN: {client.last4Ssn || "No indicado"}</small></td><td>{client.serviceDate || "No indicada"}</td><td><span>{client.city || "Sin ciudad"}</span><small>{client.state} {client.zip}</small></td><td><span>{client.email || "Sin correo"}</span><small>{client.phone || "Sin teléfono"}</small></td><td>{[client.socialServices && "Social", client.immigration && "Immigration", client.healthAndWellness && "Health"].filter(Boolean).join(", ") || "No asignados"}</td><td className="actions"><button className="text-button" onClick={() => setHistoryClient(client)}>Ver ficha</button><button className="text-button" onClick={() => openEdit(client)}>Editar</button><button className="text-button danger" onClick={() => remove(client)}>Eliminar</button></td></tr>)}</tbody></table>}</div>
    <p className="storage-note">Los expedientes se sincronizan con la base de datos central. Por seguridad, el sistema solo conserva los últimos cuatro dígitos del SSN.</p>
  </section>{isFormOpen && <ClientFormModal form={form} editing={Boolean(editingClient)} update={update} updateFile={updateFile} close={() => setIsFormOpen(false)} save={save} />}{historyClient && <ClientHistoryModal client={historyClient} services={historyServices} close={() => setHistoryClient(null)} edit={() => { setHistoryClient(null); openEdit(historyClient); }} />}</main>;
}

function parseCsv(text: string): LegacyRow[] { const lines: string[][] = [[]]; let value = ""; let quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { lines.at(-1)?.push(value); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index += 1; lines.at(-1)?.push(value); value = ""; lines.push([]); } else value += char; } lines.at(-1)?.push(value); const [headers = [], ...data] = lines; return data.filter((row) => row.some((cell) => cell.trim())).map((row) => Object.fromEntries(headers.map((header, index) => [header.trim(), (row[index] || "").trim()]))); }
function value(row: LegacyRow, key: string) { const item = row[key]?.trim() || ""; return item === "-" ? "" : item; }
function hasValue(row: LegacyRow, key: string) { return Boolean(value(row, key)); }
function dateValue(row: LegacyRow, key: string) { const item = value(row, key).replace(/ 00:00:00$/, ""); if (/^\d{4}-\d{2}-\d{2}$/.test(item)) return item; const match = item.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/); if (!match) return ""; const year = Number(match[3]); return `${year < 100 ? (year < 40 ? 2000 + year : 1900 + year) : year}-${match[1].padStart(2, "0")}-${match[2].padStart(2, "0")}`; }
function numberValue(row: LegacyRow, key: string) { return value(row, key).replace(/[^\d.]/g, ""); }
function importRow(row: LegacyRow): Client | null {
  const primary = "Full_Name" in row; const oldFormat = "Client_ID" in row; const sourceId = value(row, oldFormat ? "Client_ID" : "ClientID") || `LEGACY-${value(row, "ID")}`;
  if (!sourceId || sourceId === "LEGACY-") return null;
  const fullName = primary ? value(row, "Full_Name") : [value(row, "First_Name"), value(row, "Last_Name")].filter(Boolean).join(" ");
  const digits = value(row, primary ? "SSN" : "ID_Number").replace(/\D/g, "");
  const notes = primary ? [value(row, "Notes"), value(row, "Service_Notes"), value(row, "Comments"), value(row, "Comment")].filter(Boolean).join("\n\n") : [value(row, "Notes"), value(row, "Referred_by") && `Referred by: ${value(row, "Referred_by")}`].filter(Boolean).join("\n\n");
  const sensitiveColumn = primary ? "SSN" : "ID_Number"; const legacyData = Object.fromEntries(Object.entries(row).filter(([key]) => key !== sensitiveColumn));
  return { ...initialForm, id: crypto.randomUUID(), createdAt: new Date().toISOString(), clientId: `C-${sourceId}`, serviceDate: dateValue(row, primary ? "Service_Date" : "Date_Entered"), fullName: fullName || `Nombre no indicado (${sourceId})`, dateOfBirth: dateValue(row, primary ? "DOB" : "Date_of_Birth"), last4Ssn: digits.slice(-4), ethnicity: primary ? value(row, "Ethinicity") : "", gender: value(row, primary ? "Gender" : "Sex"), address: value(row, "Address"), city: value(row, "City"), state: value(row, "State"), zip: value(row, oldFormat ? "ZIP_Code" : "Zip"), phone: primary ? value(row, "Phone") : value(row, "Mobile_Phone") || value(row, "Home_Phone") || value(row, "Work_Phone"), email: value(row, primary ? "Email" : "Email_Address") || value(row, "Email"), nationality: value(row, "Nationality"), householdSize: primary ? numberValue(row, "Household_Size") : String((Number(numberValue(row, "Adults_at_Home")) || 0) + (Number(numberValue(row, "Children_at_Home")) || 0)), children: numberValue(row, primary ? "Children" : "Children_at_Home"), adults: numberValue(row, primary ? "Adults" : "Adults_at_Home"), seniors: numberValue(row, "Seniors"), spouseName: value(row, primary ? "Spouse_Name" : "Husband_Wife"), maritalStatus: value(row, "Marital_Status"), immigrationStatus: value(row, "Immigration_Status"), income: numberValue(row, "Income"), socialServices: hasValue(row, "Social_Services"), otherServices: hasValue(row, "Other_Svcs"), immigration: hasValue(row, "Immigration"), healthAndWellness: hasValue(row, "Health"), workersResourceCenter: hasValue(row, "Workers_Resource"), educationalEmpowerment: hasValue(row, "Education"), caseNotes: notes, legacyData } as Client;
}

function ClientHistoryModal({ client, services, close, edit }: { client: Client; services: { food: ServiceRecord[]; clothing: ServiceRecord[] }; close: () => void; edit: () => void }) {
  const name = normalizedName(client.fullName); const documents = documentNames(client);
  const history = [
    ...services.food.filter((item) => normalizedName(item.fullName || "") === name).map((item) => ({ ...item, type: "General Food Distribution", details: `Hogar: ${item.children || 0} niños, ${item.adults || 0} adultos, ${item.seniors || 0} seniors` })),
    ...services.clothing.filter((item) => normalizedName(item.fullName || "") === name).map((item) => ({ ...item, type: "Clothing Drive", details: `Total del hogar: ${item.totalHousehold || "No indicado"}` })),
  ].sort((a, b) => `${b.date || ""}${b.createdAt || ""}`.localeCompare(`${a.date || ""}${a.createdAt || ""}`));
  const requested = [[client.socialServices, "Social Services"], [client.otherServices, "Other Services"], [client.immigration, "Immigration"], [client.healthAndWellness, "Health And Wellness"], [client.workersResourceCenter, "Workers Resource Center"], [client.educationalEmpowerment, "Educational Empowerment"]].filter(([selected]) => selected).map(([, label]) => label);
  return <div className="modal-backdrop" role="presentation"><section className="modal history-modal" role="dialog" aria-modal="true" aria-labelledby="client-history-title"><div className="modal-heading"><div><p className="eyebrow">Expediente del cliente</p><h2 id="client-history-title">Historial integral</h2></div><button className="close-button" aria-label="Cerrar" onClick={close}>×</button></div>
    <div className="history-profile"><div className="history-photo">{client.photo ? <img src={storedUrl(client.photo)} alt={`Foto de ${client.fullName}`} /> : <span>{client.fullName.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("") || "C"}</span>}</div><div><h3>{client.fullName || "Cliente sin nombre"}</h3><p>{client.clientId} · SSN: {client.last4Ssn || "No indicado"}</p><p>{[client.phone, client.email].filter(Boolean).join(" · ") || "Sin contacto registrado"}</p></div><button className="secondary-button" onClick={edit}>Modificar ficha</button></div>
    <div className="history-grid"><div><strong>Datos personales</strong><span>Nacimiento: {client.dateOfBirth || "No indicado"}</span><span>{client.gender || "Género no indicado"} · {client.ethnicity || "Etnicidad no indicada"}</span><span>{client.nationality || "Nacionalidad no indicada"}</span></div><div><strong>Dirección</strong><span>{client.address || "No indicada"}</span><span>{[client.city, client.state, client.zip].filter(Boolean).join(", ") || "Ubicación no indicada"}</span></div><div><strong>Hogar</strong><span>{client.householdSize || "0"} integrantes</span><span>{client.children || "0"} niños · {client.adults || "0"} adultos · {client.seniors || "0"} seniors</span></div></div>
    <section className="history-section"><h3>Servicios recibidos</h3>{history.length ? <div className="history-timeline">{history.map((item, index) => <article className="history-event" key={`${item.type}-${item.id || index}`}><strong>{item.type}</strong><span>{item.date || "Fecha no indicada"}</span><p>{item.details}</p>{item.address && <small>{item.address}</small>}</article>)}</div> : <p className="history-empty">No hay atenciones Food o Clothing vinculadas a este nombre.</p>}</section>
    <section className="history-section"><h3>Servicios solicitados</h3><p>{requested.length ? requested.join(" · ") : "No hay servicios solicitados registrados."}</p></section>
    <section className="history-section"><h3>Notas del caso</h3><p className="case-notes">{client.caseNotes || "No hay notas registradas."}</p></section>
    <section className="history-section"><h3>Documentos</h3>{documents.length ? <ul className="history-documents">{documents.map((document, index) => <li key={`${document}-${index}`}>{document.includes("/") ? <a href={storedUrl(document)} target="_blank" rel="noreferrer">{fileLabel(document)}</a> : document}</li>)}</ul> : <p className="history-empty">No hay documentos registrados.</p>}</section>
    <section className="history-section audit-section"><h3>Auditoría</h3><p>Creado por: <strong>{client.createdBy || "Registro histórico"}</strong> · {new Date(client.createdAt).toLocaleString("es-DO")}</p><p>Última modificación: <strong>{client.updatedBy || client.createdBy || "No disponible"}</strong> · {client.updatedAt ? new Date(client.updatedAt).toLocaleString("es-DO") : "Sin modificaciones registradas"}</p></section>
  </section></div>;
}

function ClientFormModal({ form, editing, update, updateFile, close, save }: { form: ClientForm; editing: boolean; update: <K extends keyof ClientForm>(key: K, value: ClientForm[K]) => void; updateFile: (index: number, file: File | null) => void; close: () => void; save: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-backdrop" role="presentation"><section className="modal client-modal" role="dialog" aria-modal="true" aria-labelledby="client-form-title"><div className="modal-heading"><h2 id="client-form-title">{editing ? "Editar cliente" : "Nuevo cliente"}</h2><button className="close-button" aria-label="Cerrar" onClick={close}>×</button></div><form onSubmit={save}>
    <h3>Información de servicio</h3><div className="form-grid"><Field label="Client ID"><input value={form.clientId || "Se genera al guardar"} readOnly /></Field><Field label="Service Date"><input type="date" value={form.serviceDate} onChange={(e) => update("serviceDate", e.target.value)} required /></Field><Field label="Full Name"><input value={form.fullName} onChange={(e) => update("fullName", e.target.value)} required /></Field><Field label="Date Of Birth"><input type="date" value={form.dateOfBirth} onChange={(e) => update("dateOfBirth", e.target.value)} /></Field><Field label="Last 4 SSN"><input inputMode="numeric" maxLength={4} value={form.last4Ssn} onChange={(e) => update("last4Ssn", e.target.value.replace(/\D/g, "").slice(0, 4))} /></Field><Field label="Ethnicity"><input value={form.ethnicity} onChange={(e) => update("ethnicity", e.target.value)} /></Field><Field label="Gender"><select value={form.gender} onChange={(e) => update("gender", e.target.value)}><option value="">Seleccione</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></Field></div>
    <h3>Dirección y contacto</h3><div className="form-grid"><Field label="Address" full><input value={form.address} onChange={(e) => update("address", e.target.value)} /></Field><Field label="City"><input value={form.city} onChange={(e) => update("city", e.target.value)} /></Field><Field label="State"><input value={form.state} onChange={(e) => update("state", e.target.value)} /></Field><Field label="Zip"><input value={form.zip} onChange={(e) => update("zip", e.target.value)} /></Field><Field label="Phone"><input value={form.phone} onChange={(e) => update("phone", e.target.value)} /></Field><Field label="Email" full><input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></Field><Field label="Nationality"><input value={form.nationality} onChange={(e) => update("nationality", e.target.value)} /></Field></div>
    <h3>Hogar e información personal</h3><div className="form-grid"><Field label="Household Size"><input type="number" min="0" value={form.householdSize} onChange={(e) => update("householdSize", e.target.value)} /></Field><Field label="Children"><input type="number" min="0" value={form.children} onChange={(e) => update("children", e.target.value)} /></Field><Field label="Adults"><input type="number" min="0" value={form.adults} onChange={(e) => update("adults", e.target.value)} /></Field><Field label="Seniors"><input type="number" min="0" value={form.seniors} onChange={(e) => update("seniors", e.target.value)} /></Field><Field label="Spouse Name"><input value={form.spouseName} onChange={(e) => update("spouseName", e.target.value)} /></Field><Field label="Marital Status"><input value={form.maritalStatus} onChange={(e) => update("maritalStatus", e.target.value)} /></Field><Field label="Immigration Status"><input value={form.immigrationStatus} onChange={(e) => update("immigrationStatus", e.target.value)} /></Field><Field label="Income $"><input type="number" min="0" step="0.01" value={form.income} onChange={(e) => update("income", e.target.value)} /></Field></div>
    <h3>Servicios solicitados</h3><div className="service-grid"><Check label="Social Services" checked={form.socialServices} onChange={(v) => update("socialServices", v)} /><Check label="Other Services" checked={form.otherServices} onChange={(v) => update("otherServices", v)} /><Check label="Immigration" checked={form.immigration} onChange={(v) => update("immigration", v)} /><Check label="Health And Wellness" checked={form.healthAndWellness} onChange={(v) => update("healthAndWellness", v)} /><Check label="Workers Resource Center" checked={form.workersResourceCenter} onChange={(v) => update("workersResourceCenter", v)} /><Check label="Educational Empowerment" checked={form.educationalEmpowerment} onChange={(v) => update("educationalEmpowerment", v)} /></div>
    <h3>Foto, archivos y notas</h3><PhotoCapture photo={form.photo} updatePhoto={(photo) => update("photo", photo)} /><div className="file-grid">{form.files.map((file, index) => <label className="file-field" key={index}>File{index + 1}<span>{file ? fileLabel(file) : "Sin archivos seleccionados"}</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx" onChange={(e) => updateFile(index, e.target.files?.[0] || null)} /><small>Seleccionar y guardar archivo</small></label>)}</div><Field label="Case Notes" full><textarea rows={4} value={form.caseNotes} onChange={(e) => update("caseNotes", e.target.value)} /></Field>
    <div className="form-actions"><button type="button" className="cancel-button" onClick={close}>Cancelar</button><button type="submit">{editing ? "Guardar cambios" : "Registrar cliente"}</button></div>
  </form></section></div>;
}
function Field({ label, children, full = false }: { label: string; children: React.ReactNode; full?: boolean }) { return <label className={full ? "full-width" : ""}>{label}{children}</label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="service-check"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />{label}</label>; }
function PhotoCapture({ photo, updatePhoto }: { photo: string; updatePhoto: (photo: string) => void }) {
  const videoRef = useRef<HTMLVideoElement>(null); const [stream, setStream] = useState<MediaStream | null>(null); const [cameraError, setCameraError] = useState("");
  function stopCamera() { stream?.getTracks().forEach((track) => track.stop()); setStream(null); }
  async function openCamera() { try { setCameraError(""); setStream(await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false })); } catch { setCameraError("No se pudo acceder a la cámara. Verifique los permisos del navegador."); } }
  function takePhoto() { const video = videoRef.current; if (!video) return; const canvas = document.createElement("canvas"); canvas.width = video.videoWidth || 640; canvas.height = video.videoHeight || 480; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); updatePhoto(canvas.toDataURL("image/jpeg", 0.8)); stopCamera(); }
  useEffect(() => { if (stream && videoRef.current) { videoRef.current.srcObject = stream; videoRef.current.play().catch(() => setCameraError("No se pudo iniciar la cámara.")); } return () => { stream?.getTracks().forEach((track) => track.stop()); }; }, [stream]);
  return <div className="photo-capture"><strong>Foto</strong>{photo && <img src={storedUrl(photo)} alt="Foto del cliente" />} {stream && <video ref={videoRef} muted playsInline />}<div><button type="button" className="secondary-button" onClick={stream ? takePhoto : openCamera}>{stream ? "Tomar fotografía" : "Abrir cámara"}</button>{stream && <button type="button" className="text-button" onClick={stopCamera}>Cancelar cámara</button>}{photo && <button type="button" className="text-button danger" onClick={() => updatePhoto("")}>Eliminar foto</button>}</div>{cameraError && <small className="form-error">{cameraError}</small>}</div>;
}
