"use client";

import { useEffect, useMemo, useState } from "react";
import Sidebar from "../components/sidebar";
import { loadRemote } from "../lib/remote-records";

type Item = { id?: string; fullName?: string; firstName?: string; lastName?: string; clientName?: string; city?: string; state?: string; status?: string; active?: string; profile?: string; date?: string; serviceDate?: string; followUpDate?: string; amount?: string; createdAt?: string; socialServices?: boolean; otherServices?: boolean; immigration?: boolean; healthAndWellness?: boolean; workersResourceCenter?: boolean; educationalEmpowerment?: boolean };
type Row = { id: string; module: string; name: string; date: string; city: string; state: string; service: string; status: string; profile: string; amount: number; detail: string };
const read = (key: string): Item[] => { try { return JSON.parse(window.localStorage.getItem(key) || "[]") as Item[]; } catch { return []; } };
const name = (item: Item) => item.fullName || item.clientName || [item.firstName, item.lastName].filter(Boolean).join(" ") || "Sin nombre";
const servicesForClient = (item: Item) => [[item.socialServices, "Social Services"], [item.otherServices, "Other Services"], [item.immigration, "Immigration"], [item.healthAndWellness, "Health And Wellness"], [item.workersResourceCenter, "Workers Resource Center"], [item.educationalEmpowerment, "Educational Empowerment"]].filter(([selected]) => selected).map(([, label]) => label).join(", ") || "Cliente";

export default function AdvancedSearch() {
  const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [service, setService] = useState(""); const [city, setCity] = useState(""); const [status, setStatus] = useState(""); const [profile, setProfile] = useState(""); const [minDonation, setMinDonation] = useState(""); const [maxDonation, setMaxDonation] = useState("");
  useEffect(() => { let active = true; const local = { clients: read("uccw_clients"), cases: read("uccw_case_control"), donors: read("uccw_donors"), volunteers: read("uccw_volunteers"), food: read("uccw_general_food_distribution"), clothing: read("uccw_clothing_drive"), users: read("uccw_users") }; Promise.all([loadRemote<Item>("clients", local.clients), loadRemote<Item>("cases", local.cases), loadRemote<Item>("donors", local.donors), loadRemote<Item>("volunteers", local.volunteers), loadRemote<Item>("food", local.food), loadRemote<Item>("clothing", local.clothing)]).then(([clients, cases, donors, volunteers, food, clothing]) => { if (!active) return; const data: Row[] = [ ...clients.map((item) => ({ id: `client-${item.id}`, module: "Clientes", name: name(item), date: item.serviceDate || "", city: item.city || "", state: item.state || "", service: servicesForClient(item), status: "", profile: "", amount: 0, detail: item.city || "" })), ...cases.map((item) => ({ id: `case-${item.id}`, module: "Control de casos", name: name(item), date: item.followUpDate || "", city: "", state: "", service: "Seguimiento", status: item.status || "", profile: "", amount: 0, detail: item.status || "" })), ...donors.map((item) => ({ id: `donor-${item.id}`, module: "Donaciones", name: name(item), date: item.date || "", city: item.city || "", state: item.state || "", service: "Donación", status: "", profile: "", amount: Number(item.amount) || 0, detail: item.amount ? `$${Number(item.amount).toLocaleString("en-US", { minimumFractionDigits: 2 })}` : "" })), ...volunteers.map((item) => ({ id: `volunteer-${item.id}`, module: "Voluntariado", name: name(item), date: item.date || "", city: item.city || "", state: item.state || "", service: "Voluntariado", status: item.status || "", profile: "", amount: 0, detail: item.status || "" })), ...food.map((item) => ({ id: `food-${item.id}`, module: "Servicios", name: name(item), date: item.date || "", city: "", state: "", service: "Food Distribution", status: "", profile: "", amount: 0, detail: "Distribución de alimentos" })), ...clothing.map((item) => ({ id: `clothing-${item.id}`, module: "Servicios", name: name(item), date: item.date || "", city: "", state: "", service: "Clothing Drive", status: "", profile: "", amount: 0, detail: "Distribución de ropa" })), ...local.users.map((item) => ({ id: `user-${item.id}`, module: "Usuarios", name: name(item), date: item.createdAt || "", city: item.city || "", state: "", service: "", status: item.status || item.active || "", profile: item.profile || "", amount: 0, detail: item.profile || "" })) ]; setRows(data); }); return () => { active = false; }; }, []);
  const options = useMemo(() => ({ cities: [...new Set(rows.map((row) => row.city).filter(Boolean))].sort(), services: [...new Set(rows.map((row) => row.service).filter(Boolean))].sort(), statuses: [...new Set(rows.map((row) => row.status).filter(Boolean))].sort(), profiles: [...new Set(rows.map((row) => row.profile).filter(Boolean))].sort() }), [rows]);
  const visible = useMemo(() => rows.filter((row) => { const text = query.trim().toLowerCase(); const matchText = !text || [row.name, row.module, row.city, row.state, row.service, row.status, row.profile].some((value) => value.toLowerCase().includes(text)); const matchDate = (!from || (row.date && row.date >= from)) && (!to || (row.date && row.date <= to)); const matchAmount = (!minDonation || row.amount >= Number(minDonation)) && (!maxDonation || row.amount <= Number(maxDonation)); return matchText && matchDate && (!service || row.service === service) && (!city || row.city === city) && (!status || row.status === status) && (!profile || row.profile === profile) && matchAmount; }), [rows, query, from, to, service, city, status, profile, minDonation, maxDonation]);
  function reset() { setQuery(""); setFrom(""); setTo(""); setService(""); setCity(""); setStatus(""); setProfile(""); setMinDonation(""); setMaxDonation(""); }
  return <main className="app-shell clients-page"><Sidebar active="busqueda" /><section className="clients-content"><div className="page-heading"><div><p className="eyebrow">Consulta consolidada</p><h1>Búsqueda avanzada</h1><p>Combina filtros para encontrar información en todos los módulos del sistema.</p></div><button className="cancel-button" onClick={reset}>Limpiar filtros</button></div><section className="filter-panel"><div className="filter-grid"><label>Buscar<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nombre, módulo o dato" /></label><label>Desde<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>Hasta<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><label>Servicio<select value={service} onChange={(event) => setService(event.target.value)}><option value="">Todos</option>{options.services.map((item) => <option key={item}>{item}</option>)}</select></label><label>Ciudad<select value={city} onChange={(event) => setCity(event.target.value)}><option value="">Todas</option>{options.cities.map((item) => <option key={item}>{item}</option>)}</select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{options.statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label>Perfil<select value={profile} onChange={(event) => setProfile(event.target.value)}><option value="">Todos</option>{options.profiles.map((item) => <option key={item}>{item}</option>)}</select></label><label>Donación mínima<input type="number" min="0" value={minDonation} onChange={(event) => setMinDonation(event.target.value)} /></label><label>Donación máxima<input type="number" min="0" value={maxDonation} onChange={(event) => setMaxDonation(event.target.value)} /></label></div></section><div className="clients-toolbar"><span>{visible.length} resultado{visible.length === 1 ? "" : "s"}</span></div><div className="table-card">{visible.length ? <table><thead><tr><th>Módulo</th><th>Registro</th><th>Fecha</th><th>Servicio</th><th>Ubicación / Estado</th><th>Perfil / Monto</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id}><td>{row.module}</td><td><strong>{row.name}</strong><small>{row.detail}</small></td><td>{row.date || "No indicada"}</td><td>{row.service || "No aplica"}</td><td>{[row.city, row.state, row.status].filter(Boolean).join(" · ") || "No indicado"}</td><td>{row.profile || (row.amount ? `$${row.amount.toLocaleString("en-US", { minimumFractionDigits: 2 })}` : "No aplica")}</td></tr>)}</tbody></table> : <div className="empty-state"><h2>No hay coincidencias</h2><p>Prueba ajustando o limpiando los filtros.</p></div>}</div></section></main>;
}
