"use client";

import { useEffect, useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import Sidebar from "../components/sidebar";
import { loadRemote } from "../lib/remote-records";

type Client = { id?: string; fullName?: string; city?: string; state?: string; serviceDate?: string; createdAt?: string; socialServiceDetails?: string[]; legalImmigrationDetails?: string[]; workerResourceDetails?: string[]; educationalEmpowermentDetails?: string[]; healthWellnessDetails?: string[] };
type Donor = { id?: string; firstName?: string; lastName?: string; date?: string; amount?: string; createdAt?: string };
type Volunteer = { id?: string; firstName?: string; lastName?: string; status?: string; duties?: string; hours?: string; createdAt?: string };
type Service = { id?: string; date?: string; fullName?: string; address?: string; children?: string; adults?: string; seniors?: string; totalHousehold?: string; createdAt?: string };
type ReportData = { clients: Client[]; donors: Donor[]; volunteers: Volunteer[]; food: Service[]; clothing: Service[] };
const emptyData: ReportData = { clients: [], donors: [], volunteers: [], food: [], clothing: [] };
const read = <T,>(key: string): T[] => { try { return JSON.parse(window.localStorage.getItem(key) || "[]") as T[]; } catch { return []; } };
const number = (value?: string) => Number(value) || 0;
const dateKey = (value?: string) => value?.match(/^\d{4}-\d{2}/)?.[0] || "";
const labelMonth = (key: string) => key ? new Intl.DateTimeFormat("es-DO", { month: "short", year: "numeric" }).format(new Date(`${key}-01T00:00:00`)) : "Sin fecha";

function BarChart({ rows, color = "#1769aa" }: { rows: { label: string; value: number; detail?: string }[]; color?: string }) {
  const max = Math.max(...rows.map((row) => row.value), 1);
  return <div className="bar-chart" role="img" aria-label="Gráfico de barras">{rows.map((row) => <div className="bar-row" key={row.label}><div className="bar-label"><span>{row.label}</span><strong>{row.value.toLocaleString("en-US")}</strong></div><div className="bar-track"><i style={{ width: `${Math.max((row.value / max) * 100, row.value ? 4 : 0)}%`, backgroundColor: color }} /></div>{row.detail && <small>{row.detail}</small>}</div>)}</div>;
}

export default function ReportsDashboard() {
  const [data, setData] = useState<ReportData>(emptyData); const [updatedAt, setUpdatedAt] = useState<string | null>(null); const [serviceFilter, setServiceFilter] = useState(""); const [subserviceFilter, setSubserviceFilter] = useState("");
  function refresh() { Promise.all([loadRemote<Client>("clients"), loadRemote<Donor>("donors"), loadRemote<Volunteer>("volunteers"), loadRemote<Service>("food"), loadRemote<Service>("clothing")]).then(([clients, donors, volunteers, food, clothing]) => { setData({ clients, donors, volunteers, food, clothing }); setUpdatedAt(new Date().toLocaleString("es-DO")); }); }
  useEffect(() => { refresh(); }, []);
  const totals = useMemo(() => ({ clients: data.clients.length, services: data.food.length + data.clothing.length, population: data.food.reduce((sum, record) => sum + number(record.children) + number(record.adults) + number(record.seniors), 0) + data.clothing.reduce((sum, record) => sum + number(record.totalHousehold), 0), donations: data.donors.reduce((sum, donor) => sum + number(donor.amount), 0) }), [data]);
  const monthly = useMemo(() => { const source = [...data.clients.map((item) => item.serviceDate || item.createdAt), ...data.food.map((item) => item.date || item.createdAt), ...data.clothing.map((item) => item.date || item.createdAt)]; const grouped = source.map(dateKey).filter(Boolean).reduce<Record<string, number>>((result, key) => ({ ...result, [key]: (result[key] || 0) + 1 }), {}); return Object.entries(grouped).sort(([a], [b]) => a.localeCompare(b)).slice(-6).map(([key, value]) => ({ label: labelMonth(key), value })); }, [data]);
  const donationMonthly = useMemo(() => { const grouped = data.donors.map((item) => ({ key: dateKey(item.date || item.createdAt), amount: number(item.amount) })).filter((item) => item.key).reduce<Record<string, number>>((result, item) => ({ ...result, [item.key]: (result[item.key] || 0) + item.amount }), {}); return Object.entries(grouped).sort(([a], [b]) => a.localeCompare(b)).slice(-6).map(([key, value]) => ({ label: labelMonth(key), value: Number(value.toFixed(2)) })); }, [data.donors]);
  const services = useMemo(() => [{ label: "Food Distribution", value: data.food.length, detail: `${data.food.reduce((sum, item) => sum + number(item.children) + number(item.adults) + number(item.seniors), 0)} personas` }, { label: "Clothing Drive", value: data.clothing.length, detail: `${data.clothing.reduce((sum, item) => sum + number(item.totalHousehold), 0)} personas del hogar` }], [data]);
  const zones = useMemo(() => { const totalsByCity = data.clients.reduce<Record<string, number>>((result, client) => { const city = client.city?.trim() || "Sin ciudad"; result[city] = (result[city] || 0) + 1; return result; }, {}); return Object.entries(totalsByCity).sort(([, a], [, b]) => b - a).slice(0, 6).map(([label, value]) => ({ label, value })); }, [data.clients]);
  const population = useMemo(() => [{ label: "Niños", value: data.food.reduce((sum, item) => sum + number(item.children), 0) }, { label: "Adultos", value: data.food.reduce((sum, item) => sum + number(item.adults), 0) }, { label: "Seniors", value: data.food.reduce((sum, item) => sum + number(item.seniors), 0) }, { label: "Hogares - ropa", value: data.clothing.reduce((sum, item) => sum + number(item.totalHousehold), 0) }], [data]);
  const categoryDetails = useMemo(() => ({ "Social Services": data.clients.flatMap((item) => item.socialServiceDetails || []), "Legal / Immigration": data.clients.flatMap((item) => item.legalImmigrationDetails || []), "Worker Resource Center": data.clients.flatMap((item) => item.workerResourceDetails || []), "Educational Empowerment": data.clients.flatMap((item) => item.educationalEmpowermentDetails || []), "Health / Wellness / Events": data.clients.flatMap((item) => item.healthWellnessDetails || []) }), [data.clients]);
  const subserviceOptions = useMemo(() => serviceFilter ? [...new Set(categoryDetails[serviceFilter as keyof typeof categoryDetails])].sort() : [], [categoryDetails, serviceFilter]);
  const filteredClients = useMemo(() => data.clients.filter((client) => { if (!serviceFilter) return true; const details = serviceFilter === "Social Services" ? client.socialServiceDetails : serviceFilter === "Legal / Immigration" ? client.legalImmigrationDetails : serviceFilter === "Worker Resource Center" ? client.workerResourceDetails : serviceFilter === "Educational Empowerment" ? client.educationalEmpowermentDetails : client.healthWellnessDetails; return Boolean(details?.length && (!subserviceFilter || details.includes(subserviceFilter))); }), [data.clients, serviceFilter, subserviceFilter]);
  const serviceSummary = useMemo(() => Object.entries(categoryDetails).map(([label, values]) => ({ label, value: new Set(values).size, detail: `${values.length} selecciones` })), [categoryDetails]);
  const selectedClients = serviceFilter ? filteredClients : data.clients;
  function exportExcel() { const book = XLSX.utils.book_new(); const add = (name: string, rows: Record<string, unknown>[]) => XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), name); add("Resumen", [{ Indicador: "Clientes atendidos", Valor: totals.clients }, { Indicador: "Donaciones", Valor: totals.donations }, { Indicador: "Voluntarios", Valor: data.volunteers.length }, { Indicador: "Voluntarios activos", Valor: data.volunteers.filter((item) => item.status === "Active").length }, { Indicador: "Distribuciones de servicios", Valor: totals.services }, { Indicador: "Población atendida", Valor: totals.population }]); add("Clientes atendidos", data.clients.map((item) => ({ Cliente: item.fullName || "", Ciudad: item.city || "", Estado: item.state || "", "Fecha de servicio": item.serviceDate || "", "Registro creado": item.createdAt || "" }))); add("Donaciones", data.donors.map((item) => ({ Donante: [item.firstName, item.lastName].filter(Boolean).join(" "), Fecha: item.date || "", Monto: number(item.amount), "Registro creado": item.createdAt || "" }))); add("Voluntariado", data.volunteers.map((item) => ({ Voluntario: [item.firstName, item.lastName].filter(Boolean).join(" "), Estado: item.status || "", Funciones: item.duties || "", Horas: number(item.hours), "Registro creado": item.createdAt || "" }))); add("Distrib. alimentos", data.food.map((item) => ({ Fecha: item.date || "", Cliente: item.fullName || "", Dirección: item.address || "", Niños: number(item.children), Adultos: number(item.adults), Seniors: number(item.seniors), "Total hogar": number(item.children) + number(item.adults) + number(item.seniors) }))); add("Distrib. ropa", data.clothing.map((item) => ({ Fecha: item.date || "", Cliente: item.fullName || "", "Total hogar": number(item.totalHousehold) }))); XLSX.writeFile(book, `UCCW-reportes-${new Date().toISOString().slice(0, 10)}.xlsx`); }
  function exportPdf() { const pdf = new jsPDF({ unit: "pt", format: "letter" }); let y = 48; const line = (text: string, bold = false) => { if (y > 735) { pdf.addPage(); y = 48; } pdf.setFont("helvetica", bold ? "bold" : "normal"); pdf.text(text, 42, y); y += bold ? 22 : 17; }; pdf.setFontSize(18); line("UCCW - Reporte operativo", true); pdf.setFontSize(10); line(`Generado: ${new Date().toLocaleString("es-DO")}`); y += 8; pdf.setFontSize(13); line("Resumen", true); pdf.setFontSize(10); [["Clientes atendidos", totals.clients], ["Donaciones registradas", `$${totals.donations.toLocaleString("en-US", { maximumFractionDigits: 2 })}`], ["Voluntarios registrados", data.volunteers.length], ["Voluntarios activos", data.volunteers.filter((item) => item.status === "Active").length], ["Distribuciones de servicios", totals.services], ["Población atendida", totals.population]].forEach(([label, value]) => line(`${label}: ${value}`)); y += 8; pdf.setFontSize(13); line("Distribución de servicios", true); pdf.setFontSize(10); services.forEach((item) => line(`${item.label}: ${item.value} registros (${item.detail})`)); y += 8; pdf.setFontSize(13); line("Clientes atendidos por zona", true); pdf.setFontSize(10); (zones.length ? zones : [{ label: "Sin datos", value: 0 }]).forEach((item) => line(`${item.label}: ${item.value} clientes`)); y += 8; pdf.setFontSize(13); line("Población atendida", true); pdf.setFontSize(10); population.forEach((item) => line(`${item.label}: ${item.value}`)); pdf.save(`UCCW-reporte-${new Date().toISOString().slice(0, 10)}.pdf`); }
  return <main className="app-shell clients-page"><Sidebar active="reportes" /><section className="clients-content"><div className="page-heading"><div><p className="eyebrow">Análisis operativo</p><h1>Reportes</h1><p>Indicadores de atención por período, servicio, zona y población atendida.</p></div><div className="report-actions"><button className="cancel-button" onClick={refresh}>Actualizar</button><button className="secondary-button" onClick={exportExcel}>Exportar Excel</button><button onClick={exportPdf}>Exportar PDF</button></div></div>
    <div className="metric-grid"><article><span>Clientes registrados</span><strong>{totals.clients.toLocaleString("en-US")}</strong></article><article><span>Clientes filtrados</span><strong>{selectedClients.length.toLocaleString("en-US")}</strong></article><article><span>Sub-servicios disponibles</span><strong>{serviceSummary.reduce((sum, item) => sum + item.value, 0).toLocaleString("en-US")}</strong></article><article><span>Donaciones registradas</span><strong>${totals.donations.toLocaleString("en-US", { maximumFractionDigits: 0 })}</strong></article></div>
    <section className="filter-panel report-service-filters"><div className="filter-grid"><label>Servicio principal<select value={serviceFilter} onChange={(event) => { setServiceFilter(event.target.value); setSubserviceFilter(""); }}><option value="">Todos</option>{Object.keys(categoryDetails).map((item) => <option key={item}>{item}</option>)}</select></label><label>Sub-servicio<select value={subserviceFilter} onChange={(event) => setSubserviceFilter(event.target.value)} disabled={!serviceFilter}><option value="">Todos</option>{subserviceOptions.map((item) => <option key={item}>{item}</option>)}</select></label></div></section>
    <div className="report-grid enhanced-report-grid"><section className="table-card report-section chart-section"><h2>Atenciones por mes</h2><p>Clientes y servicios registrados durante los últimos seis meses con actividad.</p>{monthly.length ? <BarChart rows={monthly} /> : <div className="empty-state"><p>Aún no hay fechas para graficar.</p></div>}</section><section className="table-card report-section chart-section"><h2>Donaciones por mes</h2><p>Monto total donado en los últimos seis meses con actividad.</p>{donationMonthly.length ? <BarChart rows={donationMonthly.map((item) => ({ ...item, value: Number(item.value.toFixed(0)), detail: `$${item.value.toLocaleString("en-US", { minimumFractionDigits: 2 })}` }))} color="#0f766e" /> : <div className="empty-state"><p>Aún no hay donaciones fechadas.</p></div>}</section><section className="table-card report-section chart-section"><h2>Atenciones por servicio</h2><p>Distribución por tipo de servicio.</p><BarChart rows={services} color="#1b7f74" /></section><section className="table-card report-section chart-section"><h2>Clientes por zona</h2><p>Principales ciudades según expedientes registrados.</p>{zones.length ? <BarChart rows={zones} color="#7c3aed" /> : <div className="empty-state"><p>Aún no hay zonas registradas.</p></div>}</section><section className="table-card report-section chart-section"><h2>Población atendida</h2><p>Desglose basado en las distribuciones de alimentos y ropa.</p><BarChart rows={population} color="#d97706" /></section></div>
    <p className="storage-note">Última actualización: {updatedAt || "Cargando…"}. Los gráficos se calculan con la información sincronizada desde Supabase.</p>
  </section></main>;
}
