"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Sidebar from "../components/sidebar";
import { deleteRemote, loadRemote, saveRemote } from "../lib/remote-records";

type UserForm = { userId: string; profile: string; name: string; firstName: string; address: string; city: string; zipCode: string; email: string; phone: string; mobilePhone: string; password: string; active: "Yes" | "No" };
type User = UserForm & { id: string; createdAt: string };
const storageKey = "uccw_users";
const initialForm: UserForm = { userId: "", profile: "", name: "", firstName: "", address: "", city: "", zipCode: "", email: "", phone: "", mobilePhone: "", password: "", active: "Yes" };

function normalize(item: Partial<User>): User { const id = item.id || crypto.randomUUID(); return { ...initialForm, ...item, userId: item.userId || `U-${id.slice(0, 8).toUpperCase()}`, id, createdAt: item.createdAt || new Date().toISOString() }; }
function nextId(users: User[]) { const highest = users.reduce((max, user) => Math.max(max, Number(user.userId.match(/\d+$/)?.[0]) || 0), 0); return `U-${String(highest + 1).padStart(5, "0")}`; }
function validPassword(value: string) { return value.length >= 6 && /[a-z]/.test(value) && /[A-Z]/.test(value) && /\d/.test(value); }

export default function UserManager() {
  const [users, setUsers] = useState<User[]>([]); const [search, setSearch] = useState(""); const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<User | null>(null); const [form, setForm] = useState<UserForm>(initialForm); const [error, setError] = useState(""); const [importStatus, setImportStatus] = useState(""); const importRef = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; let local: User[] = []; try { local = JSON.parse(window.localStorage.getItem(storageKey) || "[]").map(normalize); } catch { /* Empty fallback. */ } loadRemote<User>("users", local).then((records) => { if (active) persist(records.map(normalize)); }); return () => { active = false; }; }, []);
  function persist(next: User[]) { setUsers(next); window.localStorage.setItem(storageKey, JSON.stringify(next)); }
  function openNew() { setEditing(null); setError(""); setForm(initialForm); setIsOpen(true); }
  function openEdit(user: User) { setEditing(user); setError(""); setForm({ ...user }); setIsOpen(true); }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if ((!editing || form.password) && !validPassword(form.password)) { setError("La contraseña debe tener 6 caracteres o más, una minúscula, una mayúscula y un número."); return; } const record = editing ? { ...editing, ...form, password: form.password || editing.password } : { id: crypto.randomUUID(), createdAt: new Date().toISOString(), ...form, userId: nextId(users) }; persist(editing ? users.map((user) => user.id === editing.id ? record : user) : [record, ...users]); saveRemote("users", record); setIsOpen(false); }
  function remove(user: User) { if (window.confirm(`¿Eliminar el usuario ${user.firstName} ${user.name}?`)) { persist(users.filter((item) => item.id !== user.id)); deleteRemote("users", user.id); } }
  async function importUsers(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const rows = parseCsv(await file.text()); const imported = rows.filter((row) => row.email).map((row) => ({ id: crypto.randomUUID(), createdAt: new Date().toISOString(), userId: `U-${String(row.id || "").padStart(5, "0")}`, profile: mapProfile(row.profiles_id), name: row.name || "", firstName: row.firstname || "", address: row.address || "", city: row.city || "", zipCode: row.zip_code || "", email: row.email.toLowerCase(), phone: row.phone || "", mobilePhone: row.mobile_phone || "", password: "", active: row.active === "1" || row.active?.toLowerCase() === "yes" ? "Yes" as const : "No" as const })); if (!imported.length) { setImportStatus("No se encontraron usuarios válidos en el archivo."); return; } if (!window.confirm(`Se importarán ${imported.length} usuarios. Las contraseñas heredadas no se transferirán. ¿Desea continuar?`)) return; const byEmail = new Map(users.map((user) => [user.email.toLowerCase(), user])); imported.forEach((user) => { const existing = byEmail.get(user.email); byEmail.set(user.email, existing ? { ...existing, ...user, id: existing.id, password: existing.password } : user); }); const next = [...byEmail.values()]; persist(next); setImportStatus(`Importando ${imported.length} usuarios…`); try { for (let index = 0; index < imported.length; index += 100) { const response = await fetch("/api/records/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ records: imported.slice(index, index + 100) }) }); if (!response.ok) throw new Error(); } setImportStatus(`${imported.length} usuarios importados correctamente.`); } catch { setImportStatus(`${imported.length} usuarios cargados localmente. Aplique la migración de Supabase para sincronizarlos.`); } }
  const visible = useMemo(() => { const text = search.trim().toLowerCase(); return text ? users.filter((user) => [user.userId, user.profile, user.name, user.firstName, user.email, user.city].some((value) => value.toLowerCase().includes(text))) : users; }, [users, search]);
  return <main className="app-shell clients-page"><Sidebar active="usuarios" /><section className="clients-content">
    <div className="page-heading"><div><p className="eyebrow">Administration</p><h1>Users</h1><p>Gestiona los usuarios con acceso al sistema.</p></div><div className="heading-actions"><input ref={importRef} type="file" accept=".csv,text/csv" hidden onChange={(event) => void importUsers(event)} /><button className="secondary-button" onClick={() => importRef.current?.click()}>Importar CSV</button><button onClick={openNew}>+ Add new</button></div></div>
    <div className="clients-toolbar"><input aria-label="Buscar usuarios" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre, perfil, correo o ciudad" /><span>{visible.length} usuario{visible.length === 1 ? "" : "s"}</span></div>
    {importStatus && <p className="storage-note">{importStatus}</p>}<div className="table-card">{visible.length === 0 ? <div className="empty-state"><h2>No hay usuarios registrados</h2><p>Agrega el primer usuario para comenzar.</p></div> : <table><thead><tr><th>User ID</th><th>Profile</th><th>Name</th><th>Email</th><th>Phone</th><th>Active</th><th aria-label="Acciones"></th></tr></thead><tbody>{visible.map((user) => <tr key={user.id}><td>{user.userId}</td><td>{user.profile}</td><td><strong>{user.firstName} {user.name}</strong><small>{user.city || "Sin ciudad"}</small></td><td>{user.email}</td><td>{user.mobilePhone || user.phone || "No indicado"}</td><td><span className={`status ${user.active === "Yes" ? "active-status" : "inactive-status"}`}>{user.active}</span></td><td className="actions"><button className="text-button" onClick={() => openEdit(user)}>Editar</button><button className="text-button danger" onClick={() => remove(user)}>Eliminar</button></td></tr>)}</tbody></table>}</div>
    <p className="storage-note">El directorio de usuarios se sincroniza con Supabase. Para crear acceso al login real, cada usuario debe recibir una contraseña nueva mediante Supabase Auth.</p>
  </section>{isOpen && <div className="modal-backdrop" role="presentation"><section className="modal service-modal user-modal" role="dialog" aria-modal="true" aria-labelledby="user-form-title"><div className="modal-heading"><h2 id="user-form-title">{editing ? "Editar usuario" : "Add new"}</h2><button className="close-button" aria-label="Cerrar" onClick={() => setIsOpen(false)}>×</button></div><form onSubmit={save}><div className="form-grid"><Field label="User ID"><input value={form.userId || "Se genera al guardar"} readOnly /></Field><Field label="Profile *"><select value={form.profile} onChange={(event) => setForm({ ...form, profile: event.target.value })} required><option value="">Seleccione</option><option>Administrator</option><option>Staff</option><option>Volunteer</option></select></Field><Field label="Name *"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Firstname *"><input value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} required /></Field><Field label="Address" full><input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></Field><Field label="City"><input value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} /></Field><Field label="Zip Code"><input value={form.zipCode} onChange={(event) => setForm({ ...form, zipCode: event.target.value })} /></Field><Field label="Email *"><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></Field><Field label="Phone"><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></Field><Field label="Mobile Phone"><input value={form.mobilePhone} onChange={(event) => setForm({ ...form, mobilePhone: event.target.value })} /></Field><Field label={editing ? "Nueva contraseña (opcional)" : "Password *"} full><input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} minLength={6} required={!editing} /><small>At least 6 characters - Lowercase + Uppercase + Numbers</small></Field><Field label="Active *"><select value={form.active} onChange={(event) => setForm({ ...form, active: event.target.value as UserForm["active"] })}><option>No</option><option>Yes</option></select></Field></div>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="cancel-button" onClick={() => setIsOpen(false)}>Cancelar</button><button type="submit">{editing ? "Guardar cambios" : "Add new"}</button></div></form></section></div>}</main>;
}
function Field({ label, children, full = false }: { label: string; children: React.ReactNode; full?: boolean }) { return <label className={full ? "full-width" : ""}>{label}{children}</label>; }
function parseCsv(text: string) { const lines: string[][] = [[]]; let value = ""; let quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { lines.at(-1)?.push(value); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index += 1; lines.at(-1)?.push(value); value = ""; lines.push([]); } else value += char; } lines.at(-1)?.push(value); const [headers = [], ...data] = lines; return data.filter((row) => row.some((cell) => cell.trim())).map((row) => Object.fromEntries(headers.map((header, index) => [header.trim(), (row[index] || "").trim()]))) as Record<string, string>[]; }
function mapProfile(value?: string) { const text = (value || "").toLowerCase(); return text.includes("admin") ? "Administrator" : text.includes("volunteer") ? "Volunteer" : "Staff"; }
