"use client";

import { ChangeEvent, useRef, useState } from "react";
import * as XLSX from "xlsx";
import Sidebar from "../components/sidebar";
import { loadRemote } from "../lib/remote-records";

type Item = Record<string, unknown> & { id?: string; createdAt?: string };
type Resource = "clients" | "cases" | "donors" | "volunteers" | "food" | "clothing" | "users";
const modules: { resource: Resource; sheet: string; title: string; storage: string }[] = [{ resource: "clients", sheet: "Clientes", title: "Clientes", storage: "uccw_clients" }, { resource: "cases", sheet: "Casos", title: "Control de casos", storage: "uccw_case_control" }, { resource: "donors", sheet: "Donantes", title: "Donantes", storage: "uccw_donors" }, { resource: "volunteers", sheet: "Voluntarios", title: "Voluntarios", storage: "uccw_volunteers" }, { resource: "food", sheet: "Food Distribution", title: "Food Distribution", storage: "uccw_general_food_distribution" }, { resource: "clothing", sheet: "Clothing Drive", title: "Clothing Drive", storage: "uccw_clothing_drive" }, { resource: "users", sheet: "Usuarios", title: "Usuarios", storage: "uccw_users" }];
const read = (key: string): Item[] => { try { return JSON.parse(window.localStorage.getItem(key) || "[]") as Item[]; } catch { return []; } };
const moduleForSheet = (name: string) => modules.find((module) => module.sheet.toLowerCase() === name.trim().toLowerCase());
const safeRows = (rows: Item[]) => rows.map((row) => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, Array.isArray(value) || (value && typeof value === "object") ? JSON.stringify(value) : value])));
const restoreValues = (record: Item) => Object.fromEntries(Object.entries(record).map(([key, value]) => { if (typeof value !== "string" || !/^[\[{]/.test(value.trim())) return [key, value]; try { return [key, JSON.parse(value)]; } catch { return [key, value]; } }));

export default function BackupManager() {
  const [status, setStatus] = useState(""); const [selected, setSelected] = useState<Resource | "all">("all"); const inputRef = useRef<HTMLInputElement>(null);
  async function exportBackup() { setStatus("Preparando respaldo desde Supabase…"); const workbook = XLSX.utils.book_new(); try { for (const module of modules) { const records = await loadRemote<Item>(module.resource); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(safeRows(records)), module.sheet); } XLSX.writeFile(workbook, `UCCW-respaldo-${new Date().toISOString().slice(0, 10)}.xlsx`); setStatus("Respaldo Excel descargado correctamente."); } catch { setStatus("No fue posible generar el respaldo. Vuelva a intentar."); } }
  async function importWorkbook(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setStatus("Leyendo archivo Excel…"); try { const workbook = XLSX.read(await file.arrayBuffer(), { type: "array" }); const imports: { module: typeof modules[number]; records: Item[] }[] = []; for (const sheetName of workbook.SheetNames) { const module = moduleForSheet(sheetName) || (selected === "all" ? undefined : modules.find((item) => item.resource === selected)); if (!module || (selected !== "all" && module.resource !== selected)) continue; const records = XLSX.utils.sheet_to_json<Item>(workbook.Sheets[sheetName], { defval: "" }).filter((record) => Object.values(record).some((value) => String(value).trim())); if (records.length) imports.push({ module, records: records.map((record) => ({ ...restoreValues(record), id: String(record.id || crypto.randomUUID()), createdAt: String(record.createdAt || new Date().toISOString()) })) }); }
      if (!imports.length) { setStatus("No se encontraron hojas compatibles. Use los nombres de hojas del respaldo UCCW."); return; }
      const total = imports.reduce((sum, item) => sum + item.records.length, 0); if (!window.confirm(`Se importarán o restaurarán ${total} registros. Los identificadores existentes se actualizarán. ¿Desea continuar?`)) { setStatus("Importación cancelada."); return; }
      let completed = 0; for (const item of imports) { for (let index = 0; index < item.records.length; index += 100) { const response = await fetch(`/api/records/${item.module.resource}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ records: item.records.slice(index, index + 100) }) }); if (!response.ok) throw new Error(); completed += Math.min(100, item.records.length - index); setStatus(`Restaurando ${completed} de ${total} registros…`); } }
      setStatus(`Importación completada: ${completed} registros procesados.`);
    } catch { setStatus("No fue posible importar el archivo. Verifique que sea un Excel válido y que la sesión siga activa."); }
  }
  const selectedTitle = selected === "all" ? "todas las hojas compatibles" : modules.find((module) => module.resource === selected)?.title;
  return <main className="app-shell clients-page"><Sidebar active="respaldo" /><section className="clients-content"><div className="page-heading"><div><p className="eyebrow">Protección de información</p><h1>Respaldo e importación</h1><p>Exporta una copia completa, restaura un respaldo o importa listas desde Excel.</p></div></div><div className="backup-grid"><section className="dashboard-panel"><h2>Exportar respaldo</h2><p>Genera un archivo Excel con una hoja por módulo: clientes, casos, donantes, voluntarios, servicios y usuarios.</p><button onClick={() => void exportBackup()}>Descargar respaldo Excel</button></section><section className="dashboard-panel"><h2>Restaurar o importar Excel</h2><p>Selecciona un respaldo UCCW o una lista Excel con hojas compatibles. Los registros con el mismo identificador se actualizan.</p><label className="import-select">Módulo a importar<select value={selected} onChange={(event) => setSelected(event.target.value as Resource | "all")}><option value="all">Todas las hojas</option>{modules.map((module) => <option value={module.resource} key={module.resource}>{module.title}</option>)}</select></label><input ref={inputRef} type="file" accept=".xlsx,.xls" hidden onChange={(event) => void importWorkbook(event)} /><button className="secondary-button" onClick={() => inputRef.current?.click()}>Seleccionar archivo Excel</button><small>Selección actual: {selectedTitle}.</small></section></div>{status && <p className="storage-note backup-status">{status}</p>}<section className="dashboard-panel import-guide"><h2>Formato de importación</h2><p>La forma más segura es exportar primero un respaldo, editar la hoja correspondiente en Excel y volver a importarla. Mantén las columnas <strong>id</strong> y <strong>createdAt</strong> para restaurar o actualizar los registros existentes; elimina <strong>id</strong> para crear registros nuevos.</p></section></section></main>;
}
