"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Sidebar from "../components/sidebar";
import { deleteRemote, loadRemote, saveRemote } from "../lib/remote-records";

type CaseForm = { caseNumber: string; clientName: string; status: "Abierto" | "En proceso" | "Cerrado"; assignedTo: string; followUpDate: string; notes: string };
type CaseRecord = CaseForm & { id: string; createdAt: string; createdBy?: string; updatedAt?: string; updatedBy?: string };
const storageKey = "uccw_case_control";
const initialForm: CaseForm = { caseNumber: "", clientName: "", status: "Abierto", assignedTo: "", followUpDate: "", notes: "" };

function normalize(item: Partial<CaseRecord>): CaseRecord { const id = item.id || crypto.randomUUID(); return { ...initialForm, ...item, caseNumber: item.caseNumber || `CASE-${id.slice(0, 8).toUpperCase()}`, id, createdAt: item.createdAt || new Date().toISOString() }; }
function nextNumber(records: CaseRecord[]) { const highest = records.reduce((maximum, record) => Math.max(maximum, Number(record.caseNumber.match(/\d+$/)?.[0]) || 0), 0); return `CASE-${String(highest + 1).padStart(5, "0")}`; }

export default function CaseManager() {
  const [cases, setCases] = useState<CaseRecord[]>([]); const [search, setSearch] = useState(""); const [isFormOpen, setIsFormOpen] = useState(false); const [editing, setEditing] = useState<CaseRecord | null>(null); const [form, setForm] = useState<CaseForm>(initialForm);
  useEffect(() => { let active = true; loadRemote<CaseRecord>("cases").then((records) => { if (active) setCases(records.map(normalize)); }); return () => { active = false; }; }, []);
  function persist(records: CaseRecord[]) { setCases(records); }
  function update<K extends keyof CaseForm>(key: K, value: CaseForm[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function openNew() { setEditing(null); setForm(initialForm); setIsFormOpen(true); }
  function openEdit(record: CaseRecord) { setEditing(record); setForm({ ...record }); setIsFormOpen(true); }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const record = editing ? { ...editing, ...form } : { id: crypto.randomUUID(), createdAt: new Date().toISOString(), ...form, caseNumber: nextNumber(cases) }; persist(editing ? cases.map((item) => item.id === editing.id ? record : item) : [record, ...cases]); saveRemote("cases", record); setIsFormOpen(false); }
  function remove(record: CaseRecord) { if (window.confirm(`¿Eliminar el caso ${record.caseNumber}?`)) { persist(cases.filter((item) => item.id !== record.id)); deleteRemote("cases", record.id); } }
  const visible = useMemo(() => { const text = search.trim().toLowerCase(); return text ? cases.filter((record) => [record.caseNumber, record.clientName, record.status, record.assignedTo].some((value) => value.toLowerCase().includes(text))) : cases; }, [cases, search]);
  return <main className="app-shell clients-page"><Sidebar active="casos" /><section className="clients-content">
    <div className="page-heading"><div><p className="eyebrow">Seguimiento</p><h1>Control de casos</h1><p>Administra el estado, responsable y próximos seguimientos de cada caso.</p></div><button onClick={openNew}>+ Nuevo caso</button></div>
    <div className="clients-toolbar"><input aria-label="Buscar casos" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por número de caso, cliente, estado o responsable" /><span>{visible.length} caso{visible.length === 1 ? "" : "s"}</span></div>
    <div className="table-card">{visible.length === 0 ? <div className="empty-state"><h2>No hay casos registrados</h2><p>Crea un caso para iniciar su seguimiento.</p></div> : <table><thead><tr><th>Número de caso</th><th>Cliente</th><th>Estado</th><th>Responsable</th><th>Fecha de seguimiento</th><th aria-label="Acciones"></th></tr></thead><tbody>{visible.map((record) => <tr key={record.id}><td><strong>{record.caseNumber}</strong></td><td>{record.clientName || "Sin cliente asignado"}</td><td><span className={`case-status ${record.status === "Cerrado" ? "closed" : record.status === "En proceso" ? "in-progress" : "open"}`}>{record.status}</span></td><td>{record.assignedTo || "Sin asignar"}</td><td>{record.followUpDate || "No indicada"}</td><td className="actions"><button className="text-button" onClick={() => openEdit(record)}>Editar</button><button className="text-button danger" onClick={() => remove(record)}>Eliminar</button></td></tr>)}</tbody></table>}</div>
    <p className="storage-note">Los casos se sincronizan con la base de datos central una vez aplicada la migración de Supabase.</p>
  </section>{isFormOpen && <div className="modal-backdrop" role="presentation"><section className="modal case-modal" role="dialog" aria-modal="true" aria-labelledby="case-form-title"><div className="modal-heading"><h2 id="case-form-title">{editing ? "Editar caso" : "Nuevo caso"}</h2><button className="close-button" aria-label="Cerrar" onClick={() => setIsFormOpen(false)}>×</button></div><form onSubmit={save}><div className="form-grid"><Field label="Número de caso"><input value={form.caseNumber || "Se genera al guardar"} readOnly /></Field><Field label="Estado"><select value={form.status} onChange={(event) => update("status", event.target.value as CaseForm["status"])}><option>Abierto</option><option>En proceso</option><option>Cerrado</option></select></Field><Field label="Cliente" full><input value={form.clientName} onChange={(event) => update("clientName", event.target.value)} placeholder="Nombre completo del cliente" /></Field><Field label="Responsable"><input value={form.assignedTo} onChange={(event) => update("assignedTo", event.target.value)} placeholder="Persona responsable" required /></Field><Field label="Fecha de seguimiento"><input type="date" value={form.followUpDate} onChange={(event) => update("followUpDate", event.target.value)} required /></Field><Field label="Notas" full><textarea rows={5} value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Detalles o próximo paso del caso" /></Field></div>{editing && <div className="audit-summary"><strong>Auditoría</strong><span>Creado por {editing.createdBy || "Registro histórico"} · {new Date(editing.createdAt).toLocaleString("es-DO")}</span><span>Última modificación: {editing.updatedBy || editing.createdBy || "No disponible"}{editing.updatedAt ? ` · ${new Date(editing.updatedAt).toLocaleString("es-DO")}` : ""}</span></div>}<div className="form-actions"><button type="button" className="cancel-button" onClick={() => setIsFormOpen(false)}>Cancelar</button><button type="submit">{editing ? "Guardar cambios" : "Registrar caso"}</button></div></form></section></div>}</main>;
}

function Field({ label, children, full = false }: { label: string; children: React.ReactNode; full?: boolean }) { return <label className={full ? "full-width" : ""}>{label}{children}</label>; }
