"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import Sidebar from "../components/sidebar";
import { loadRemote } from "../lib/remote-records";

type Item = { id?: string; createdAt?: string; fullName?: string; firstName?: string; lastName?: string; name?: string; amount?: string; status?: string; active?: string; children?: string; adults?: string; seniors?: string; totalHousehold?: string; files?: string[]; caseNumber?: string; clientName?: string; assignedTo?: string; followUpDate?: string; date?: string };
type Activity = { id: string; title: string; detail: string; createdAt: string; href: string };
type Alert = { id: string; title: string; detail: string; tone: "urgent" | "warning" | "info"; href: string };
const read = (key: string): Item[] => { try { return JSON.parse(window.localStorage.getItem(key) || "[]"); } catch { return []; } };
const itemName = (item: Item) => item.fullName || [item.firstName, item.lastName].filter(Boolean).join(" ") || item.name || "Registro sin nombre";
const household = (item: Item) => item.totalHousehold ? Number(item.totalHousehold) || 0 : [item.children, item.adults, item.seniors].reduce((sum, value) => sum + (Number(value) || 0), 0);

export default function DashboardOverview() {
  const [data, setData] = useState({ clients: [] as Item[], cases: [] as Item[], donors: [] as Item[], volunteers: [] as Item[], users: [] as Item[], food: [] as Item[], clothing: [] as Item[] });
  useEffect(() => { const local = { clients: read("uccw_clients"), cases: read("uccw_case_control"), donors: read("uccw_donors"), volunteers: read("uccw_volunteers"), users: read("uccw_users"), food: read("uccw_general_food_distribution"), clothing: read("uccw_clothing_drive") }; Promise.all([loadRemote<Item>("clients", local.clients), loadRemote<Item>("cases", local.cases), loadRemote<Item>("donors", local.donors), loadRemote<Item>("volunteers", local.volunteers), loadRemote<Item>("food", local.food), loadRemote<Item>("clothing", local.clothing)]).then(([clients, cases, donors, volunteers, food, clothing]) => setData({ clients, cases, donors, volunteers, users: local.users, food, clothing })); }, []);
  const metrics = useMemo(() => ({ clients: data.clients.length, donors: data.donors.length, volunteers: data.volunteers.filter((volunteer) => volunteer.status === "Active").length, users: data.users.filter((user) => user.active === "Yes").length }), [data]);
  const activity = useMemo(() => {
    const collections: [Item[], string, string, string][] = [[data.clients, "Cliente", "Nuevo cliente", "/clientes"], [data.donors, "Donación", "Nueva donación", "/donantes"], [data.food, "Servicio", "Food Distribution", "/servicios"], [data.clothing, "Servicio", "Clothing Drive", "/servicios/clothing-drive"]];
    return collections.flatMap(([items, label, action, href]) => items.map((item) => ({ id: `${label}-${item.id || item.createdAt || itemName(item)}`, title: `${action}: ${itemName(item)}`, detail: label, createdAt: item.createdAt || "", href }))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 6);
  }, [data]);
  const alerts = useMemo(() => {
    const today = new Date(); today.setHours(0, 0, 0, 0); const nextWeek = new Date(today); nextWeek.setDate(nextWeek.getDate() + 7);
    const alertRows: Alert[] = [];
    data.cases.filter((record) => record.status !== "Cerrado" && (!record.followUpDate || new Date(`${record.followUpDate}T00:00:00`) <= nextWeek)).forEach((record) => { const followUp = record.followUpDate ? new Date(`${record.followUpDate}T00:00:00`) : null; const overdue = !followUp || followUp < today; alertRows.push({ id: `case-${record.id || record.caseNumber}`, title: `Seguimiento ${overdue ? "pendiente" : "próximo"}: ${record.caseNumber || "Caso"}`, detail: `${record.clientName || "Cliente sin asignar"}${record.assignedTo ? ` · Responsable: ${record.assignedTo}` : ""}${record.followUpDate ? ` · ${record.followUpDate}` : " · Sin fecha"}`, tone: overdue ? "urgent" : "warning", href: "/casos" }); });
    data.clients.filter((client) => !client.files?.some(Boolean)).forEach((client) => alertRows.push({ id: `document-${client.id || itemName(client)}`, title: `Documentos faltantes: ${itemName(client)}`, detail: "El expediente no tiene documentos adjuntos.", tone: "warning", href: "/clientes" }));
    data.volunteers.filter((volunteer) => volunteer.status === "Inactive" || volunteer.status === "Inactivo").forEach((volunteer) => alertRows.push({ id: `volunteer-${volunteer.id || itemName(volunteer)}`, title: `Voluntario inactivo: ${itemName(volunteer)}`, detail: "Revisar disponibilidad o actualizar su estado.", tone: "info", href: "/voluntarios" }));
    [...data.food.map((item) => ({ ...item, activity: "Food Distribution", href: "/servicios" })), ...data.clothing.map((item) => ({ ...item, activity: "Clothing Drive", href: "/servicios/clothing-drive" }))].filter((item) => item.date && new Date(`${item.date}T00:00:00`) >= today && new Date(`${item.date}T00:00:00`) <= nextWeek).forEach((item) => alertRows.push({ id: `activity-${item.id || `${item.activity}-${item.fullName}`}`, title: `Actividad próxima: ${item.activity}`, detail: `${itemName(item)} · ${item.date}`, tone: "info", href: item.href }));
    return alertRows.sort((a, b) => ({ urgent: 0, warning: 1, info: 2 }[a.tone] - { urgent: 0, warning: 1, info: 2 }[b.tone]));
  }, [data]);
  const todayServices = useMemo(() => { const today = new Intl.DateTimeFormat("sv-SE", { timeZone: "America/Santo_Domingo" }).format(new Date()); const food = data.food.filter((item) => item.date === today); const clothing = data.clothing.filter((item) => item.date === today); return { today, food, clothing, people: [...food, ...clothing].reduce((sum, item) => sum + household(item), 0) }; }, [data.food, data.clothing]);
  return <main className="app-shell dashboard-page"><Sidebar active="inicio" /><section className="dashboard-overview">
    <div className="dashboard-intro"><div><p className="eyebrow">Panel operativo</p><h1>Bienvenido a UCCW</h1><p>Consulta un resumen de la gestión y registra nuevas atenciones rápidamente.</p></div><Link className="secondary-button" href="/reportes">Ver reportes</Link></div>
    <div className="metric-grid dashboard-metrics"><article><span>Clientes registrados</span><strong>{metrics.clients}</strong></article><article><span>Donantes</span><strong>{metrics.donors}</strong></article><article><span>Voluntarios activos</span><strong>{metrics.volunteers}</strong></article><article><span>Usuarios activos</span><strong>{metrics.users}</strong></article></div>
    <section className="dashboard-panel today-services"><div className="panel-heading"><div><h2>Servicios del día</h2><p>{new Date(`${todayServices.today}T00:00:00`).toLocaleDateString("es-DO", { weekday: "long", day: "numeric", month: "long" })}</p></div><strong className="today-total">{todayServices.food.length + todayServices.clothing.length} entregas</strong></div><div className="today-service-grid"><Link href="/servicios"><span>Food Distribution</span><strong>{todayServices.food.length}</strong><small>{todayServices.food.reduce((sum, item) => sum + household(item), 0)} personas atendidas</small></Link><Link href="/servicios/clothing-drive"><span>Clothing Drive</span><strong>{todayServices.clothing.length}</strong><small>{todayServices.clothing.reduce((sum, item) => sum + household(item), 0)} personas del hogar</small></Link><div><span>Población atendida hoy</span><strong>{todayServices.people}</strong><small>En ambos servicios</small></div></div>{todayServices.food.length + todayServices.clothing.length > 0 && <ul className="today-list">{[...todayServices.food.map((item) => ({ ...item, type: "Food Distribution" })), ...todayServices.clothing.map((item) => ({ ...item, type: "Clothing Drive" }))].map((item, index) => <li key={`${item.type}-${item.id || index}`}><strong>{item.fullName || "Cliente sin nombre"}</strong><span>{item.type} · Hogar: {household(item)}</span></li>)}</ul>}</section>
    <section className="dashboard-panel alerts-panel"><div className="panel-heading"><div><h2>Avisos y recordatorios</h2><p>{alerts.length ? `${alerts.length} aviso${alerts.length === 1 ? "" : "s"} que requieren atención.` : "No hay avisos pendientes."}</p></div><Link className="text-button" href="/casos">Ver casos</Link></div>{alerts.length ? <ul className="alert-list">{alerts.slice(0, 10).map((alert) => <li key={alert.id} className={alert.tone}><Link href={alert.href}><strong>{alert.title}</strong><span>{alert.detail}</span></Link></li>)}</ul> : <div className="empty-state"><p>Todo está al día.</p></div>}</section>
    <div className="dashboard-grid"><section className="dashboard-panel"><h2>Acciones rápidas</h2><div className="quick-actions"><Link href="/clientes">+ Nuevo cliente</Link><Link href="/donantes">+ Nueva donación</Link><Link href="/voluntarios">+ Nuevo voluntario</Link><Link href="/servicios">+ Registrar distribución de alimentos</Link><Link href="/servicios/clothing-drive">+ Registrar distribución de ropa</Link></div></section><section className="dashboard-panel"><h2>Actividad reciente</h2>{activity.length ? <ul className="activity-list">{activity.map((entry) => <li key={entry.id}><Link href={entry.href}><strong>{entry.title}</strong><span>{entry.detail}{entry.createdAt ? ` · ${new Date(entry.createdAt).toLocaleDateString("es-DO")}` : ""}</span></Link></li>)}</ul> : <div className="empty-state"><p>Aún no hay actividad registrada.</p></div>}</section></div>
    <p className="storage-note">Los indicadores se actualizan desde Supabase al iniciar sesión.</p>
  </section></main>;
}
